# Generated by Django 4.2.28 on 2026-05-20 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del usuario', max_length=100)),
                ('correo', models.EmailField(help_text='Correo electrónico único', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección completa', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de creación automática')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-id'],
            },
        ),
    ]
